// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QTS.Strategy.EntityFramework;

namespace QTS.Strategy.Migrations
{
    [DbContext(typeof(QTSDbContext))]
    partial class QTSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QTS.EntityFramework.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cn")
                        .HasMaxLength(6);

                    b.Property<string>("Exchange")
                        .HasMaxLength(2);

                    b.Property<string>("Name")
                        .HasMaxLength(10);

                    b.Property<int?>("StrategyId");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("QTS.EntityFramework.Strategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GMID");

                    b.Property<string>("Name")
                        .HasMaxLength(20);

                    b.Property<string>("Type")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Strategies");
                });

            modelBuilder.Entity("QTS.EntityFramework.Instrument", b =>
                {
                    b.HasOne("QTS.EntityFramework.Strategy")
                        .WithMany("Instruments")
                        .HasForeignKey("StrategyId");
                });
#pragma warning restore 612, 618
        }
    }
}
